spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/HMS
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update # dev only
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
